---
- name: myplaybook
  hosts: app

  tasks:
    - name: apache installation
      shell: yum install httpd -y
      register: out1
    - debug: msg={{ out1.stdout }}

    - name: apache starting
      shell: service httpd start
      register: out2
    - debug: msg={{ out2.stdout }}


...

